// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ggezchain/mobile/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a048e00a95d19d49, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a048e00a95d19d49, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetMobileIndexRequest struct {
}

func (m *QueryGetMobileIndexRequest) Reset()         { *m = QueryGetMobileIndexRequest{} }
func (m *QueryGetMobileIndexRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMobileIndexRequest) ProtoMessage()    {}
func (*QueryGetMobileIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a048e00a95d19d49, []int{2}
}
func (m *QueryGetMobileIndexRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMobileIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMobileIndexRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMobileIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMobileIndexRequest.Merge(m, src)
}
func (m *QueryGetMobileIndexRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMobileIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMobileIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMobileIndexRequest proto.InternalMessageInfo

type QueryGetMobileIndexResponse struct {
	MobileIndex MobileIndex `protobuf:"bytes,1,opt,name=MobileIndex,proto3" json:"MobileIndex"`
}

func (m *QueryGetMobileIndexResponse) Reset()         { *m = QueryGetMobileIndexResponse{} }
func (m *QueryGetMobileIndexResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMobileIndexResponse) ProtoMessage()    {}
func (*QueryGetMobileIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a048e00a95d19d49, []int{3}
}
func (m *QueryGetMobileIndexResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMobileIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMobileIndexResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMobileIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMobileIndexResponse.Merge(m, src)
}
func (m *QueryGetMobileIndexResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMobileIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMobileIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMobileIndexResponse proto.InternalMessageInfo

func (m *QueryGetMobileIndexResponse) GetMobileIndex() MobileIndex {
	if m != nil {
		return m.MobileIndex
	}
	return MobileIndex{}
}

type QueryGetStoredTradeRequest struct {
	TradeIndex string `protobuf:"bytes,1,opt,name=tradeIndex,proto3" json:"tradeIndex,omitempty"`
}

func (m *QueryGetStoredTradeRequest) Reset()         { *m = QueryGetStoredTradeRequest{} }
func (m *QueryGetStoredTradeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredTradeRequest) ProtoMessage()    {}
func (*QueryGetStoredTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a048e00a95d19d49, []int{4}
}
func (m *QueryGetStoredTradeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredTradeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredTradeRequest.Merge(m, src)
}
func (m *QueryGetStoredTradeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredTradeRequest proto.InternalMessageInfo

func (m *QueryGetStoredTradeRequest) GetTradeIndex() string {
	if m != nil {
		return m.TradeIndex
	}
	return ""
}

type QueryGetStoredTradeResponse struct {
	StoredTrade StoredTrade `protobuf:"bytes,1,opt,name=storedTrade,proto3" json:"storedTrade"`
}

func (m *QueryGetStoredTradeResponse) Reset()         { *m = QueryGetStoredTradeResponse{} }
func (m *QueryGetStoredTradeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredTradeResponse) ProtoMessage()    {}
func (*QueryGetStoredTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a048e00a95d19d49, []int{5}
}
func (m *QueryGetStoredTradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredTradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredTradeResponse.Merge(m, src)
}
func (m *QueryGetStoredTradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredTradeResponse proto.InternalMessageInfo

func (m *QueryGetStoredTradeResponse) GetStoredTrade() StoredTrade {
	if m != nil {
		return m.StoredTrade
	}
	return StoredTrade{}
}

type QueryAllStoredTradeRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredTradeRequest) Reset()         { *m = QueryAllStoredTradeRequest{} }
func (m *QueryAllStoredTradeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredTradeRequest) ProtoMessage()    {}
func (*QueryAllStoredTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a048e00a95d19d49, []int{6}
}
func (m *QueryAllStoredTradeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredTradeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredTradeRequest.Merge(m, src)
}
func (m *QueryAllStoredTradeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredTradeRequest proto.InternalMessageInfo

func (m *QueryAllStoredTradeRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllStoredTradeResponse struct {
	StoredTrade []StoredTrade       `protobuf:"bytes,1,rep,name=storedTrade,proto3" json:"storedTrade"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredTradeResponse) Reset()         { *m = QueryAllStoredTradeResponse{} }
func (m *QueryAllStoredTradeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredTradeResponse) ProtoMessage()    {}
func (*QueryAllStoredTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a048e00a95d19d49, []int{7}
}
func (m *QueryAllStoredTradeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredTradeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredTradeResponse.Merge(m, src)
}
func (m *QueryAllStoredTradeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredTradeResponse proto.InternalMessageInfo

func (m *QueryAllStoredTradeResponse) GetStoredTrade() []StoredTrade {
	if m != nil {
		return m.StoredTrade
	}
	return nil
}

func (m *QueryAllStoredTradeResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ggezchain.mobile.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ggezchain.mobile.QueryParamsResponse")
	proto.RegisterType((*QueryGetMobileIndexRequest)(nil), "ggezchain.mobile.QueryGetMobileIndexRequest")
	proto.RegisterType((*QueryGetMobileIndexResponse)(nil), "ggezchain.mobile.QueryGetMobileIndexResponse")
	proto.RegisterType((*QueryGetStoredTradeRequest)(nil), "ggezchain.mobile.QueryGetStoredTradeRequest")
	proto.RegisterType((*QueryGetStoredTradeResponse)(nil), "ggezchain.mobile.QueryGetStoredTradeResponse")
	proto.RegisterType((*QueryAllStoredTradeRequest)(nil), "ggezchain.mobile.QueryAllStoredTradeRequest")
	proto.RegisterType((*QueryAllStoredTradeResponse)(nil), "ggezchain.mobile.QueryAllStoredTradeResponse")
}

func init() { proto.RegisterFile("ggezchain/mobile/query.proto", fileDescriptor_a048e00a95d19d49) }

var fileDescriptor_a048e00a95d19d49 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x6b, 0xd4, 0x40,
	0x18, 0xc6, 0x77, 0x6a, 0x2d, 0x38, 0x0b, 0x22, 0x63, 0x0f, 0x65, 0xdd, 0x46, 0x49, 0xad, 0xff,
	0xaa, 0x33, 0x6c, 0x85, 0xe2, 0x41, 0x84, 0x16, 0xb4, 0x7a, 0x28, 0xd4, 0xd5, 0x93, 0x97, 0x32,
	0xd9, 0x0c, 0xd9, 0x40, 0x92, 0x49, 0x33, 0xb3, 0xd2, 0x2a, 0x5e, 0xfa, 0x09, 0x04, 0xcf, 0x82,
	0x67, 0xc1, 0xef, 0xd1, 0x63, 0xc1, 0x8b, 0x27, 0x91, 0x5d, 0x3f, 0x86, 0x07, 0xc9, 0xcc, 0xc4,
	0xcc, 0x36, 0xc9, 0xb6, 0x78, 0x6a, 0x99, 0xf7, 0x79, 0xdf, 0xe7, 0x37, 0xef, 0x3e, 0x13, 0xd8,
	0x0d, 0x02, 0xf6, 0x6e, 0x30, 0xa4, 0x61, 0x42, 0x62, 0xee, 0x85, 0x11, 0x23, 0xfb, 0x23, 0x96,
	0x1d, 0xe2, 0x34, 0xe3, 0x92, 0xa3, 0x2b, 0xff, 0xaa, 0x58, 0x57, 0x3b, 0x8b, 0x01, 0x0f, 0xb8,
	0x2a, 0x92, 0xfc, 0x3f, 0xad, 0xeb, 0x74, 0x03, 0xce, 0x83, 0x88, 0x11, 0x9a, 0x86, 0x84, 0x26,
	0x09, 0x97, 0x54, 0x86, 0x3c, 0x11, 0xa6, 0x7a, 0x6f, 0xc0, 0x45, 0xcc, 0x05, 0xf1, 0xa8, 0x30,
	0xe3, 0xc9, 0xdb, 0x9e, 0xc7, 0x24, 0xed, 0x91, 0x94, 0x06, 0x61, 0xa2, 0xc4, 0x46, 0xbb, 0x5c,
	0xe1, 0x49, 0x69, 0x46, 0xe3, 0x62, 0xd4, 0x4a, 0xa5, 0xac, 0xff, 0xec, 0x85, 0x89, 0xcf, 0x0e,
	0x1a, 0x45, 0x42, 0xf2, 0x8c, 0xf9, 0x7b, 0x32, 0xa3, 0x3e, 0xd3, 0x22, 0x77, 0x11, 0xa2, 0x97,
	0x39, 0xca, 0xae, 0x1a, 0xdf, 0x67, 0xfb, 0x23, 0x26, 0xa4, 0xbb, 0x03, 0xaf, 0x4e, 0x9d, 0x8a,
	0x94, 0x27, 0x82, 0xa1, 0x0d, 0xb8, 0xa0, 0x31, 0x96, 0xc0, 0x0d, 0x70, 0xa7, 0xbd, 0xbe, 0x84,
	0x4f, 0x2f, 0x06, 0xeb, 0x8e, 0xad, 0xf9, 0xe3, 0x9f, 0xd7, 0x5b, 0x7d, 0xa3, 0x76, 0xbb, 0xb0,
	0xa3, 0xc6, 0x6d, 0x33, 0xb9, 0xa3, 0x64, 0x2f, 0x72, 0xcc, 0xc2, 0xcc, 0x87, 0xd7, 0x6a, 0xab,
	0xc6, 0xf4, 0x29, 0x6c, 0x5b, 0xc7, 0xc6, 0x79, 0xb9, 0xea, 0x6c, 0x89, 0x8c, 0xbd, 0xdd, 0xe7,
	0x3e, 0x2e, 0x19, 0x5e, 0xa9, 0x35, 0xbc, 0xce, 0xb7, 0x60, 0x18, 0x90, 0x03, 0xa1, 0xda, 0x4a,
	0xe9, 0x71, 0xa9, 0x6f, 0x9d, 0xd8, 0x8c, 0x53, 0xdd, 0x25, 0xa3, 0x28, 0x8f, 0x9b, 0x19, 0xad,
	0xde, 0x82, 0xd1, 0xea, 0x73, 0x7d, 0xc3, 0xb8, 0x19, 0x45, 0x35, 0x8c, 0xcf, 0x20, 0x2c, 0x73,
	0x62, 0x3c, 0x6e, 0x61, 0x1d, 0x2a, 0x9c, 0x87, 0x0a, 0xeb, 0xcc, 0x9a, 0x50, 0xe1, 0x5d, 0x1a,
	0x14, 0xbd, 0x7d, 0xab, 0xd3, 0xfd, 0x06, 0xcc, 0x65, 0x4e, 0xdb, 0x34, 0x5d, 0xe6, 0xc2, 0xff,
	0x5c, 0x06, 0x6d, 0x4f, 0xe1, 0xce, 0x29, 0xdc, 0xdb, 0x67, 0xe2, 0x6a, 0x06, 0x9b, 0x77, 0xfd,
	0xcf, 0x3c, 0xbc, 0xa8, 0x78, 0xd1, 0x11, 0x80, 0x0b, 0x3a, 0x60, 0xe8, 0x66, 0x95, 0xa7, 0x9a,
	0xe3, 0xce, 0xea, 0x19, 0x2a, 0xed, 0xe6, 0xae, 0x1d, 0x7d, 0xff, 0xfd, 0x69, 0x6e, 0x15, 0xad,
	0x90, 0x98, 0x8f, 0x04, 0x0d, 0xbd, 0x8c, 0x0e, 0x49, 0xc3, 0x0b, 0x44, 0x9f, 0xc1, 0x54, 0x20,
	0xd1, 0xfd, 0x06, 0x8f, 0xda, 0xb0, 0x77, 0x1e, 0x9c, 0x53, 0x6d, 0xc8, 0x7a, 0x8a, 0x6c, 0x0d,
	0xdd, 0x9d, 0x49, 0x66, 0x3f, 0x7e, 0xf4, 0x15, 0xc0, 0xb6, 0xf5, 0xd3, 0xcc, 0xe2, 0xab, 0x86,
	0x6c, 0x16, 0x5f, 0x4d, 0x56, 0xdc, 0x27, 0x8a, 0xef, 0x11, 0xda, 0x98, 0xc9, 0x67, 0x7f, 0x77,
	0xc8, 0xfb, 0xf2, 0x59, 0x7d, 0x40, 0x5f, 0x00, 0xbc, 0x6c, 0xcd, 0xdd, 0x8c, 0xa2, 0x46, 0xde,
	0xda, 0x47, 0xd1, 0xc8, 0x5b, 0x9f, 0xed, 0x73, 0xee, 0xd3, 0xe6, 0xdd, 0x7a, 0x7e, 0x3c, 0x76,
	0xc0, 0xc9, 0xd8, 0x01, 0xbf, 0xc6, 0x0e, 0xf8, 0x38, 0x71, 0x5a, 0x27, 0x13, 0xa7, 0xf5, 0x63,
	0xe2, 0xb4, 0xde, 0xe0, 0x20, 0x94, 0xc3, 0x91, 0x87, 0x07, 0x3c, 0xae, 0x1f, 0x77, 0x50, 0x0c,
	0x94, 0x87, 0x29, 0x13, 0xde, 0x82, 0xfa, 0xe4, 0x3e, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x4a,
	0xe5, 0xca, 0x05, 0x6d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a MobileIndex by index.
	MobileIndex(ctx context.Context, in *QueryGetMobileIndexRequest, opts ...grpc.CallOption) (*QueryGetMobileIndexResponse, error)
	// Queries a list of StoredTrade items.
	StoredTrade(ctx context.Context, in *QueryGetStoredTradeRequest, opts ...grpc.CallOption) (*QueryGetStoredTradeResponse, error)
	StoredTradeAll(ctx context.Context, in *QueryAllStoredTradeRequest, opts ...grpc.CallOption) (*QueryAllStoredTradeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.mobile.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MobileIndex(ctx context.Context, in *QueryGetMobileIndexRequest, opts ...grpc.CallOption) (*QueryGetMobileIndexResponse, error) {
	out := new(QueryGetMobileIndexResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.mobile.Query/MobileIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StoredTrade(ctx context.Context, in *QueryGetStoredTradeRequest, opts ...grpc.CallOption) (*QueryGetStoredTradeResponse, error) {
	out := new(QueryGetStoredTradeResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.mobile.Query/StoredTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StoredTradeAll(ctx context.Context, in *QueryAllStoredTradeRequest, opts ...grpc.CallOption) (*QueryAllStoredTradeResponse, error) {
	out := new(QueryAllStoredTradeResponse)
	err := c.cc.Invoke(ctx, "/ggezchain.mobile.Query/StoredTradeAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a MobileIndex by index.
	MobileIndex(context.Context, *QueryGetMobileIndexRequest) (*QueryGetMobileIndexResponse, error)
	// Queries a list of StoredTrade items.
	StoredTrade(context.Context, *QueryGetStoredTradeRequest) (*QueryGetStoredTradeResponse, error)
	StoredTradeAll(context.Context, *QueryAllStoredTradeRequest) (*QueryAllStoredTradeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) MobileIndex(ctx context.Context, req *QueryGetMobileIndexRequest) (*QueryGetMobileIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MobileIndex not implemented")
}
func (*UnimplementedQueryServer) StoredTrade(ctx context.Context, req *QueryGetStoredTradeRequest) (*QueryGetStoredTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoredTrade not implemented")
}
func (*UnimplementedQueryServer) StoredTradeAll(ctx context.Context, req *QueryAllStoredTradeRequest) (*QueryAllStoredTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoredTradeAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.mobile.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MobileIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMobileIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MobileIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.mobile.Query/MobileIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MobileIndex(ctx, req.(*QueryGetMobileIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StoredTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStoredTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StoredTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.mobile.Query/StoredTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StoredTrade(ctx, req.(*QueryGetStoredTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StoredTradeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllStoredTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StoredTradeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ggezchain.mobile.Query/StoredTradeAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StoredTradeAll(ctx, req.(*QueryAllStoredTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ggezchain.mobile.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "MobileIndex",
			Handler:    _Query_MobileIndex_Handler,
		},
		{
			MethodName: "StoredTrade",
			Handler:    _Query_StoredTrade_Handler,
		},
		{
			MethodName: "StoredTradeAll",
			Handler:    _Query_StoredTradeAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ggezchain/mobile/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMobileIndexRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMobileIndexRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMobileIndexRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetMobileIndexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMobileIndexResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMobileIndexResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MobileIndex.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredTradeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredTradeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredTradeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TradeIndex) > 0 {
		i -= len(m.TradeIndex)
		copy(dAtA[i:], m.TradeIndex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TradeIndex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredTradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredTradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredTradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.StoredTrade.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredTradeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredTradeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredTradeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredTradeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredTradeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredTradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.StoredTrade) > 0 {
		for iNdEx := len(m.StoredTrade) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StoredTrade[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMobileIndexRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetMobileIndexResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MobileIndex.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetStoredTradeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TradeIndex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetStoredTradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StoredTrade.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllStoredTradeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllStoredTradeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StoredTrade) > 0 {
		for _, e := range m.StoredTrade {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMobileIndexRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMobileIndexRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMobileIndexRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMobileIndexResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMobileIndexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMobileIndexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MobileIndex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MobileIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredTradeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredTradeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredTradeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradeIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredTradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredTradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredTradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredTrade", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StoredTrade.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredTradeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredTradeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredTradeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredTradeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredTradeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredTradeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredTrade", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoredTrade = append(m.StoredTrade, StoredTrade{})
			if err := m.StoredTrade[len(m.StoredTrade)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
